import type { Metadata } from "next";
import { Inter, Barlow } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { ThemeProvider } from "next-themes";

const interFont = Inter({ subsets: ["latin"] });
const barlowFont = Barlow({ subsets: ["latin"], weight: ['500', '700'], variable: '--font-barlow' });

export const metadata: Metadata = {
  title: "GoShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${interFont.className} ${barlowFont.variable}`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
